# application.yml (common config file)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/devdb
    username: root
    password: root

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/proddb
    username: root
    password: root

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/localdb
    username: root
    password: root
