# application.yml (common config file)
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/mydb
#     username: root
#     password: root

# ---
# spring:
#   config:
#     activate:
#       on-profile: dev
#   profiles: dev
#   datasource:
#     url: jdbc:mysql://localhost:3306/devdb
#     username: root
#     password: root

# ---
# spring:
#   config:
#     activate:
#       on-profile: prod
#   datasource:
#     url: jdbc:mysql://localhost:3306/proddb
#     username: root
#     password: root

# ---
# spring:
#   config:
#     activate:
#       on-profile: local
#   datasource:
#     url: jdbc:mysql://localhost:3306/localdb
#     username: root
#     password: root

spring:
  application:
    name: config-repo

# Common properties shared across different services
server:
  port: 8080

# If you have shared properties like database configurations, put them here
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
