spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb  # MySQL database URL
    username: root  # Database username
    password: root  # Database password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver
  jpa:
    hibernate:
      ddl-auto: update  # Automatically update schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect  # MySQL dialect for Hibernate
    show-sql: true
