server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #Need to remove this to turn off the sql.
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create-drop



# spring:
#   application:
#     name: user-service
# # Local Profile Configuration
#   config:
#     activate:
#       on-profile: local  # This section applies only when the 'local' profile is active
#   datasource:
#     url: jdbc:mysql://localhost:3306/userdb  # MySQL database URL
#     username: root  # Database username
#     password: root  # Database password
#     driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver
#   jpa:
#     hibernate:
#       ddl-auto: update  # Automatically update schema
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQL5InnoDBDialect  # MySQL dialect for Hibernate
#     show-sql: true
# ---

# # Dev Profile Configuration
# spring:
#   config:
#     activate:
#       on-profile: dev  # This section applies only when the 'dev' profile is active

#   datasource:
#     url: jdbc:mysql://dev-db-server:3306/userdb
#     username: devuser
#     password: devpassword
#     driver-class-name: com.mysql.cj.jdbc.Driver

#   jpa:
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#     show-sql: true
